= Getter
:title: JIII

:tag: bhbh

**org.openrewrite.java.migrate.guava.PreferMathAddExact**

fish

[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....


[plantuml]
....
@startuml

Recipe <|--- ConvertLogRecipe

JavaIsoVistor <|--- LogVisitor

LogVisitor <|--- Slf4jVisitor

ConvertLogRecipe  <|--- ConvertToSlf4jLogAnnotation

ConvertToSlf4jLogAnnotation::getVisitor *- "1" Slf4jVisitor: getVisitor()

class Recipe {
getDisplayName(): String
getDescription(): String
getVisitor(): TreeVisitor
}

abstract class LogVisitor {
{abstract} switchImports(): void
{abstract} getLombokTemplate() : JavaTemplate
{abstract} expectedLoggerPath() : String
{abstract} methodPath(path : String)
}

abstract class ConvertLogRecipe {
getDisplayName(annotation: String): String
getDescription(annotation: String): String
}
note left of ConvertLogRecipe::getDisplayName
 helper methods provde a template
end note

class ConvertToSlf4jLogAnnotation {
}

@enduml
....


gugu

[tabs]
====
Tab A:: Contents of Tab A.

Tab B::
+
[source,Kotlin]
--
public static void main(){

}
--

Tab C::
+
.something
[source,java]
--
public static void main(){

}
--
====