site:
  title: Antora Demo Site
  url: https://my-antora-demo-site.org
  start_page: component-singleton::index.adoc
content:
  sources:
    - url: /home/t/Code/openrewrite/rewrite-recipe-starter
      branches: HEAD
      start_path: src/docs/adoc
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - '@antora/lunr-extension'
asciidoc:
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
